# Generated by Django 5.0.7 on 2024-07-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EC_id', models.CharField(blank=True, max_length=100, null=True)),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Image', models.FileField(blank=True, null=True, upload_to='Experience')),
                ('SmallDescription', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.CharField(blank=True, max_length=100, null=True)),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('Price', models.CharField(blank=True, max_length=100, null=True)),
                ('Days', models.CharField(blank=True, max_length=100, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('EIm_id', models.CharField(blank=True, max_length=100, null=True)),
                ('EIn_id', models.CharField(blank=True, max_length=100, null=True)),
                ('EF_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.CharField(blank=True, max_length=100, null=True)),
                ('Image', models.FileField(blank=True, null=True, upload_to='ExperienceCategory')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_id', models.CharField(blank=True, max_length=100, null=True)),
                ('Image', models.FileField(blank=True, null=True, upload_to='ExperienceImages')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceIncluded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_id', models.CharField(blank=True, max_length=100, null=True)),
                ('Types', models.CharField(blank=True, max_length=100, null=True)),
                ('Lines', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
