# Generated by Django 5.0.7 on 2024-07-31 13:13

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_eid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EID',
        ),
    ]
