# Generated by Django 5.0.7 on 2024-07-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_eid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='EC_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='EF_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='EIm_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='EIn_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='experienceimages',
            name='E_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='experienceincluded',
            name='E_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
