# Generated by Django 5.0.7 on 2024-08-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_experience_ec_id_alter_experience_ef_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='View',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
