# Generated by Django 5.0.7 on 2024-08-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_experience_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceFormsA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_id', models.IntegerField(blank=True, default=0, null=True)),
                ('A1', models.TextField(blank=True, null=True)),
                ('A2', models.TextField(blank=True, null=True)),
                ('A3', models.TextField(blank=True, null=True)),
                ('A4', models.TextField(blank=True, null=True)),
                ('A5', models.TextField(blank=True, null=True)),
                ('A6', models.TextField(blank=True, null=True)),
                ('A7', models.TextField(blank=True, null=True)),
                ('A8', models.TextField(blank=True, null=True)),
                ('A9', models.TextField(blank=True, null=True)),
                ('A10', models.TextField(blank=True, null=True)),
                ('A11', models.TextField(blank=True, null=True)),
                ('A12', models.TextField(blank=True, null=True)),
                ('A13', models.TextField(blank=True, null=True)),
                ('A14', models.TextField(blank=True, null=True)),
                ('A15', models.TextField(blank=True, null=True)),
                ('A16', models.TextField(blank=True, null=True)),
                ('A17', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceFormsMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_id', models.IntegerField(blank=True, default=0, null=True)),
                ('FullName', models.TextField(blank=True, null=True)),
                ('DOB', models.DateField()),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('ContactNo', models.CharField(blank=True, max_length=100, null=True)),
                ('State', models.CharField(blank=True, max_length=100, null=True)),
                ('City', models.CharField(blank=True, max_length=100, null=True)),
                ('SOP', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceFormsQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_id', models.IntegerField(blank=True, default=0, null=True)),
                ('Q1', models.TextField(blank=True, null=True)),
                ('Q2', models.TextField(blank=True, null=True)),
                ('Q3', models.TextField(blank=True, null=True)),
                ('Q4', models.TextField(blank=True, null=True)),
                ('Q5', models.TextField(blank=True, null=True)),
                ('Q6', models.TextField(blank=True, null=True)),
                ('Q7', models.TextField(blank=True, null=True)),
                ('Q8', models.TextField(blank=True, null=True)),
                ('Q9', models.TextField(blank=True, null=True)),
                ('Q10', models.TextField(blank=True, null=True)),
                ('Q11', models.TextField(blank=True, null=True)),
                ('Q12', models.TextField(blank=True, null=True)),
                ('Q13', models.TextField(blank=True, null=True)),
                ('Q14', models.TextField(blank=True, null=True)),
                ('Q15', models.TextField(blank=True, null=True)),
                ('Q16', models.TextField(blank=True, null=True)),
                ('Q17', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
