# Generated by Django 5.0.7 on 2024-08-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_experienceformsa_experienceformsmain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienceformsa',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experienceformsq',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
