# Generated by Django 5.0.7 on 2024-08-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_experienceformsa_name_experienceformsq_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienceformsa',
            name='A1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experienceformsa',
            name='A10',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experienceformsa',
            name='A11',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experienceformsa',
            name='A12',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experienceformsa',
            name='A13',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experienceformsa',
            name='A14',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experienceformsa',
            name='A15',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experienceformsa',
            name='A16',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experienceformsa',
            name='A17',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experienceformsa',
            name='A2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experienceformsa',
            name='A3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experienceformsa',
            name='A4',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experienceformsa',
            name='A5',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experienceformsa',
            name='A6',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experienceformsa',
            name='A7',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experienceformsa',
            name='A8',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experienceformsa',
            name='A9',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experienceformsq',
            name='Q1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experienceformsq',
            name='Q10',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experienceformsq',
            name='Q11',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experienceformsq',
            name='Q12',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experienceformsq',
            name='Q13',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experienceformsq',
            name='Q14',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experienceformsq',
            name='Q15',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experienceformsq',
            name='Q16',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experienceformsq',
            name='Q17',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experienceformsq',
            name='Q2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experienceformsq',
            name='Q3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experienceformsq',
            name='Q4',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experienceformsq',
            name='Q5',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experienceformsq',
            name='Q6',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experienceformsq',
            name='Q7',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experienceformsq',
            name='Q8',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experienceformsq',
            name='Q9',
            field=models.TextField(blank=True, default=''),
        ),
    ]
