# Generated by Django 5.0.7 on 2024-08-05 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_experienceformsa_a1_alter_experienceformsa_a10_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExperienceFormsMain',
        ),
    ]
