# Generated by Django 5.0.7 on 2024-08-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_experienceformsmain'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienceformsa',
            name='City',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experienceformsa',
            name='ContactNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experienceformsa',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experienceformsa',
            name='Email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experienceformsa',
            name='FullName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experienceformsa',
            name='SOP',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experienceformsa',
            name='State',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
