# Generated by Django 5.0.7 on 2024-08-06 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_memories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Memories',
            new_name='MemoriesModel',
        ),
    ]
