# Generated by Django 5.0.7 on 2024-08-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_userdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experienceformsa',
            old_name='City',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='experienceformsa',
            old_name='State',
            new_name='Countrycode',
        ),
        migrations.AddField(
            model_name='experienceformsa',
            name='Pincode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experienceformsa',
            name='WPNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
